// Auto-generated by svg_icon_gen/generate.py.
// Do not edit by hand.

export type NgolIconName = 'arrow-down' | 'arrow-up' | 'chevron-down' | 'chevron-left' | 'chevron-right' | 'chevron-up' | 'clipboard' | 'close' | 'double-play' | 'edit' | 'folder' | 'gamepad' | 'gear' | 'history' | 'link' | 'loader' | 'lock' | 'lock-open' | 'map' | 'minus' | 'pin' | 'play' | 'plus' | 'puzzle' | 'search' | 'sort' | 'stop' | 'trash' | 'warning'

export interface NgolIconElement {
  kind: 'path' | 'polygon' | 'rect' | 'circle'
  attrs: Record<string, string>
}

export interface NgolIconDef {
  viewBox: string
  elements: NgolIconElement[]
}

export const NGOL_ICON_DEFS: Record<NgolIconName, NgolIconDef> = 
{
  "arrow-down": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M12 5v14",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "m19 12-7 7-7-7",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "arrow-up": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M12 19V5",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "m5 12 7-7 7 7",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "chevron-down": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M6 9l6 6 6-6",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "chevron-left": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M15 6l-6 6 6 6",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "chevron-right": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M9 6l6 6-6 6",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "chevron-up": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M6 15l6-6 6 6",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "clipboard": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "rect",
        "attrs": {
          "x": "8",
          "y": "2",
          "width": "8",
          "height": "4",
          "rx": "1",
          "ry": "1",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "close": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M6 6l12 12M18 6L6 18",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "double-play": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M5 6l6 4.5L5 15V6z",
          "fill": "currentColor",
          "stroke": "none"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M13 6l6 4.5-6 4.5V6z",
          "fill": "currentColor",
          "stroke": "none"
        }
      }
    ]
  },
  "edit": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "folder": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "gamepad": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "rect",
        "attrs": {
          "x": "2",
          "y": "7",
          "width": "20",
          "height": "10",
          "rx": "4",
          "ry": "4",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M7 10v4M5 12h4",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "circle",
        "attrs": {
          "cx": "16",
          "cy": "10.5",
          "r": "1",
          "fill": "currentColor",
          "stroke": "none"
        }
      },
      {
        "kind": "circle",
        "attrs": {
          "cx": "18.5",
          "cy": "13",
          "r": "1",
          "fill": "currentColor",
          "stroke": "none"
        }
      }
    ]
  },
  "gear": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "circle",
        "attrs": {
          "cx": "12",
          "cy": "12",
          "r": "3",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "history": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "circle",
        "attrs": {
          "cx": "12",
          "cy": "12",
          "r": "10",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M12 6v6l4 2",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "link": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "loader": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M12 3a9 9 0 1 1-6.36 2.64",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "lock": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "rect",
        "attrs": {
          "x": "3",
          "y": "11",
          "width": "18",
          "height": "11",
          "rx": "2",
          "ry": "2",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M7 11V7a5 5 0 0 1 10 0v4",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "lock-open": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "rect",
        "attrs": {
          "x": "3",
          "y": "11",
          "width": "18",
          "height": "11",
          "rx": "2",
          "ry": "2",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M7 11V7a5 5 0 0 1 9.9-1",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "map": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M4 6l8-3 8 3v12l-8 3-8-3V6z",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M12 3v18",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "minus": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M5 12h14",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "pin": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "circle",
        "attrs": {
          "cx": "12",
          "cy": "10",
          "r": "3",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "play": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M8 6l10 6-10 6V6z",
          "fill": "currentColor",
          "stroke": "none"
        }
      }
    ]
  },
  "plus": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M12 5v14M5 12h14",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "puzzle": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M3 7H8.5V6A3.5 3.5 0 0 1 15.5 6V7H21V10A4 4 0 0 0 21 18V21H3V7Z",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "search": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "circle",
        "attrs": {
          "cx": "11",
          "cy": "11",
          "r": "8",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M21 21l-4.35-4.35",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "sort": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "m21 16-4 4-4-4",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M17 20V4",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "m3 8 4-4 4 4",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M7 4v16",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "stop": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "rect",
        "attrs": {
          "x": "7",
          "y": "7",
          "width": "10",
          "height": "10",
          "rx": "1",
          "fill": "currentColor",
          "stroke": "none"
        }
      }
    ]
  },
  "trash": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M3 6h18",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M10 11v6M14 11v6",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  },
  "warning": {
    "viewBox": "0 0 24 24",
    "elements": [
      {
        "kind": "path",
        "attrs": {
          "d": "M12 9v4",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M12 17h.01",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      },
      {
        "kind": "path",
        "attrs": {
          "d": "M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z",
          "fill": "none",
          "stroke": "currentColor",
          "stroke-width": "2",
          "stroke-linecap": "round",
          "stroke-linejoin": "round"
        }
      }
    ]
  }
}

